cse = {
  "1933": "tgif",
  "1933 industries": "tgif",
  "1933 industries inc.": "tgif",
  "3": "safe",
  "3 sixty": "safe",
  "3 sixty risk": "safe",
  "3 sixty risk solutions": "safe",
  "3 sixty risk solutions ltd.": "safe",
  "4front": "ffnt",
  "4front ventures": "ffnt",
  "4front ventures corp.": "ffnt",
  "66": "sxx",
  "66 resources": "sxx",
  "66 resources inc.": "sxx",
  "79north": "jq",
  "79north inc.": "jq",
  "79north inc. (formerly": "jq",
  "79north inc. (formerly was": "jq",
  "79north inc. (formerly was twlv/12": "jq",
  "79north inc. (formerly was twlv/12 exploration inc. until 2020-08-18)": "jq",
  "abattis": "att",
  "abattis bioceuticals": "att",
  "abattis bioceuticals corp.": "att",
  "aca": "aca",
  "acg": "acg",
  "acrg.u": "acrg",
  "adastra": "xtrx",
  "adastra labs": "xtrx",
  "adastra labs holdings": "xtrx",
  "adastra labs holdings ltd.": "xtrx",
  "advantagewon": "aoc",
  "advantagewon oil": "aoc",
  "advantagewon oil corp.": "aoc",
  "advantex": "adx",
  "advantex marketing": "adx",
  "advantex marketing international": "adx",
  "advantex marketing international inc.": "adx",
  "adx": "adx",
  "aether": "athr",
  "aether catalyst": "athr",
  "aether catalyst solutions,": "athr",
  "aether catalyst solutions, inc.": "athr",
  "afd": "afd",
  "affinor": "afi",
  "affinor growers": "afi",
  "affinor growers inc.": "afi",
  "afi": "afi",
  "ag.un": "ag",
  "agn": "agn",
  "agn.wt": "agn",
  "agra": "agra",
  "agraflora": "agra",
  "agraflora organics": "agra",
  "agraflora organics international": "agra",
  "agraflora organics international inc": "agra",
  "agrios": "agro",
  "agrios global": "agro",
  "agrios global holdings": "agro",
  "agrios global holdings ltd.": "agro",
  "agro": "agro",
  "ahg": "ahg",
  "ajn": "ajn",
  "ajn resources": "ajn",
  "ajn resources inc.": "ajn",
  "algernon": "agn",
  "algernon pharmaceuticals": "agn",
  "algernon pharmaceuticals inc.": "agn",
  "alliance": "acg",
  "alliance growers": "acg",
  "alliance growers corp.": "acg",
  "alternate": "ahg",
  "alternate health": "ahg",
  "alternate health corp.": "ahg",
  "american": "usgd",
  "american aires": "wifi",
  "american aires inc.": "wifi",
  "american pacific": "usgd",
  "american pacific mining": "usgd",
  "american pacific mining corp.": "usgd",
  "amp": "xcx",
  "amp german": "xcx",
  "amp german cannabis": "xcx",
  "amp german cannabis group": "xcx",
  "amp german cannabis group inc.": "xcx",
  "ampd": "ampd",
  "ampd ventures": "ampd",
  "ampd ventures inc.": "ampd",
  "ams.x": "ams",
  "ansar": "afd",
  "ansar financial": "afd",
  "ansar financial and": "afd",
  "ansar financial and dev": "afd",
  "ansar financial and dev corporation": "afd",
  "aoc": "aoc",
  "api": "api",
  "app": "app",
  "appia": "api",
  "appia energy": "api",
  "appia energy corp.": "api",
  "aquarius": "asti",
  "aquarius surgical": "asti",
  "aquarius surgical technologies": "asti",
  "aquarius surgical technologies inc.": "asti",
  "arev": "arev",
  "arev nanotec": "arev",
  "arev nanotec brands": "arev",
  "arev nanotec brands inc.": "arev",
  "arev nanotec brands inc. (formerly": "arev",
  "arev nanotec brands inc. (formerly was arev/arev brands international ltd. until 2020-03-18)": "arev",
  "argo": "arq",
  "argo gold": "arq",
  "argo gold inc.": "arq",
  "arm": "arm",
  "armada": "arm",
  "armada mercantile": "arm",
  "armada mercantile ltd.": "arm",
  "armadillo": "aro",
  "armadillo resources": "aro",
  "armadillo resources ltd.": "aro",
  "aro": "aro",
  "arq": "arq",
  "asante": "ase",
  "asante gold": "ase",
  "asante gold corporation": "ase",
  "ase": "ase",
  "asia": "asia",
  "asia green": "asia",
  "asia green biotechnology": "asia",
  "asia green biotechnology corp.": "asia",
  "asia green biotechnology corp. (formerly": "asia",
  "asia green biotechnology corp. (formerly was asia/asia cannabis corp. until 2020-04-15)": "asia",
  "asti": "asti",
  "athr": "athr",
  "att": "att",
  "auag": "auag",
  "aucu": "aucu",
  "aurwest": "awr",
  "aurwest resources": "awr",
  "aurwest resources corporation": "awr",
  "aurwest resources corporation (formerly": "awr",
  "aurwest resources corporation (formerly was": "awr",
  "aurwest resources corporation (formerly was srs/shamrock enterprises inc. until 2020-01-07)": "awr",
  "ausa": "ausa",
  "australis": "ausa",
  "australis capital": "ausa",
  "australis capital inc.": "ausa",
  "auxico": "auag",
  "auxico resources": "auag",
  "auxico resources canada": "auag",
  "auxico resources canada inc.": "auag",
  "avm.x": "avm",
  "awr": "awr",
  "axiom": "aca",
  "axiom capital": "aca",
  "axiom capital advisors": "aca",
  "axiom capital advisors inc.": "aca",
  "ayl": "ayl",
  "aylen": "ayl",
  "aylen capital": "ayl",
  "aylen capital inc.": "ayl",
  "ayr.a": "ayr",
  "ayr.rt": "ayr",
  "ayr.wt": "ayr",
  "bac": "bac",
  "bactech": "bac",
  "bactech environmental": "bac",
  "bactech environmental corporation": "bac",
  "bam": "bbr",
  "bam bam": "bbr",
  "bam bam resources": "bbr",
  "bam bam resources corp.": "bbr",
  "bam bam resources corp. (formerly": "bbr",
  "bam bam resources corp. (formerly was kopr/kopr point ventures inc. until 2019-12-04)": "bbr",
  "bamm": "bamm",
  "bbm": "bbm",
  "bbr": "bbr",
  "bbt": "bbt",
  "bc": "crft",
  "bc craft": "crft",
  "bc craft supply": "crft",
  "bc craft supply co.": "crft",
  "bc craft supply co. ltd.": "crft",
  "bc craft supply co. ltd. (formerly was crft/pasha brands ltd. until 2020-05-15)": "crft",
  "bca": "bca",
  "bcfn": "bcfn",
  "bdr": "bdr",
  "bean": "bean",
  "bee": "bee",
  "bee vectoring": "bee",
  "bee vectoring technologies": "bee",
  "bee vectoring technologies international": "bee",
  "bee vectoring technologies international inc.": "bee",
  "beleave": "be",
  "beleave inc.": "be",
  "belgravia": "blgv",
  "belgravia hartford": "blgv",
  "belgravia hartford capital": "blgv",
  "belgravia hartford capital inc.": "blgv",
  "belgravia hartford capital inc. (formerly": "blgv",
  "belgravia hartford capital inc. (formerly was blgv/belgravia capital international inc. until 2019-12-20)": "blgv",
  "benchmark": "bbt",
  "benchmark botanics": "bbt",
  "benchmark botanics inc.": "bbt",
  "berkley": "bks",
  "berkley renewables": "bks",
  "berkley renewables inc.": "bks",
  "betr": "betr",
  "bets": "bets",
  "bets.wt": "bets",
  "better": "plnt",
  "better plant": "plnt",
  "better plant sciences": "plnt",
  "better plant sciences inc.": "plnt",
  "better plant sciences inc. (formerly": "plnt",
  "better plant sciences inc. (formerly was boss/the yield growth corp. until 2020-08-17)": "plnt",
  "betterlife": "betr",
  "betterlife pharma": "betr",
  "betterlife pharma inc.": "betr",
  "bev": "bev",
  "bevcanna": "bev",
  "bevcanna enterprises": "bev",
  "bevcanna enterprises inc.": "bev",
  "bexar": "bxv",
  "bexar ventures": "bxv",
  "bexar ventures inc.": "bxv",
  "bfg": "bfg",
  "bgrd.x": "bgrd",
  "bhang": "bhng",
  "bhang inc.": "bhng",
  "bhng": "bhng",
  "bhsc": "bhsc",
  "bigg": "bigg",
  "bigg digital": "bigg",
  "bigg digital assets": "bigg",
  "bigg digital assets inc": "bigg",
  "bigg digital assets inc (formerly": "bigg",
  "bigg digital assets inc (formerly was bigg/big blockchain intelligence group inc. until 2019-10-03)": "bigg",
  "bilz": "bilz",
  "bio": "bio",
  "biocure": "cure",
  "biocure technology": "cure",
  "biocure technology inc.": "cure",
  "bioharvest": "bhsc",
  "bioharvest sciences": "bhsc",
  "bioharvest sciences inc.": "bhsc",
  "biomark": "bux",
  "biomark diagnostics": "bux",
  "biomark diagnostics inc.": "bux",
  "biome": "bio",
  "biome grow": "bio",
  "biome grow inc.": "bio",
  "biosenta": "zro",
  "biosenta inc.": "zro",
  "bird": "bdr",
  "bird river": "bdr",
  "bird river resources": "bdr",
  "bird river resources inc.": "bdr",
  "bitrush": "brh",
  "bitrush corp.": "brh",
  "bjb": "bjb",
  "bks": "bks",
  "black": "tusk",
  "black tusk": "tusk",
  "black tusk resources": "tusk",
  "black tusk resources inc.": "tusk",
  "blackhawk": "blr",
  "blackhawk growth": "blr",
  "blackhawk growth corp.": "blr",
  "blackhawk growth corp. (formerly": "blr",
  "blackhawk growth corp. (formerly was": "blr",
  "blackhawk growth corp. (formerly was blr/blackhawk resource corp. until 2020-03-10)": "blr",
  "blgv": "blgv",
  "blk": "blk",
  "bllg": "bllg",
  "blo": "blo",
  "blockchain": "bcfn",
  "blockchain foundry": "bcfn",
  "blockchain foundry inc": "bcfn",
  "blocplay": "play",
  "blocplay entertainment": "play",
  "blocplay entertainment inc.": "play",
  "blok": "blk",
  "blok technologies": "blk",
  "blok technologies inc.": "blk",
  "blr": "blr",
  "blr.wt": "blr",
  "blue": "bllg",
  "blue lagoon": "bllg",
  "blue lagoon resources": "bllg",
  "blue lagoon resources inc.": "bllg",
  "blueberries": "bbm",
  "blueberries medical": "bbm",
  "blueberries medical corp.": "bbm",
  "bluesky": "btc",
  "bluesky digital": "btc",
  "bluesky digital assets": "btc",
  "bluesky digital assets corp.": "btc",
  "bnkr": "bnkr",
  "body": "bamm",
  "body and": "bamm",
  "body and mind": "bamm",
  "body and mind inc.": "bamm",
  "bolt": "bolt",
  "bolt metals": "bolt",
  "bolt metals corp.": "bolt",
  "bolt metals corp. (formerly": "bolt",
  "bolt metals corp. (formerly was": "bolt",
  "bolt metals corp. (formerly was bolt/pacific rim cobalt corp. until 2020-02-25)": "bolt",
  "bond": "bjb",
  "bond resources": "bjb",
  "bond resources inc.": "bjb",
  "brand": "bxxx",
  "brand x": "bxxx",
  "brand x lifestyle": "bxxx",
  "brand x lifestyle corp.": "bxxx",
  "brand x lifestyle corp. (formerly": "bxxx",
  "brand x lifestyle corp. (formerly was bxxx/block x capital corp. until 2020-03-27)": "bxxx",
  "brh": "brh",
  "btc": "btc",
  "btc.pr.a": "btc",
  "bucephalus": "bca",
  "bucephalus capital": "bca",
  "bucephalus capital corp.": "bca",
  "bull": "bull",
  "bullfrog": "bfg",
  "bullfrog gold": "bfg",
  "bullfrog gold corp.": "bfg",
  "bunker": "bnkr",
  "bunker hill": "bnkr",
  "bunker hill mining": "bnkr",
  "bunker hill mining corp.": "bnkr",
  "bux": "bux",
  "buzz": "buzz",
  "bwel.u": "bwel",
  "bxv": "bxv",
  "bxxx": "bxxx",
  "byrn": "byrn",
  "byrna": "byrn",
  "byrna technologies": "byrn",
  "byrna technologies inc.": "byrn",
  "byrna technologies inc. (formerly": "byrn",
  "byrna technologies inc. (formerly was": "byrn",
  "byrna technologies inc. (formerly was sdz/security devices international inc. until 2020-03-03)": "byrn",
  "c21": "cxxi",
  "c21 investments": "cxxi",
  "c21 investments inc.": "cxxi",
  "caelan": "cdn",
  "caelan capital": "cdn",
  "caelan capital inc.": "cdn",
  "caelan capital inc. (formerly": "cdn",
  "caelan capital inc. (formerly was": "cdn",
  "caelan capital inc. (formerly was cdn/caelan capital corp. until 2020-04-13)": "cdn",
  "cali": "cali",
  "california": "cgm",
  "california gold": "cgm",
  "california gold mining": "cgm",
  "california gold mining inc.": "cgm",
  "callitas": "lily",
  "callitas health": "lily",
  "callitas health inc.": "lily",
  "camarico": "cig",
  "camarico investment": "cig",
  "camarico investment group": "cig",
  "camarico investment group ltd.": "cig",
  "cameo": "cru",
  "cameo industries": "cru",
  "cameo industries corp.": "cru",
  "camp": "camp",
  "cana": "cana",
  "canada": "chv",
  "canada house": "chv",
  "canada house wellness": "chv",
  "canada house wellness group": "chv",
  "canada house wellness group inc.": "chv",
  "canadian": "bull",
  "canadian goldcamps": "camp",
  "canadian goldcamps corp.": "camp",
  "canadian goldcamps corp. (formerly": "camp",
  "canadian goldcamps corp. (formerly was": "camp",
  "canadian goldcamps corp. (formerly was abj/supreme metals corp. until 2020-08-12)": "camp",
  "canadian metals": "cme",
  "canadian metals inc.": "cme",
  "canadian overseas": "xop",
  "canadian overseas petroleum": "xop",
  "canadian overseas petroleum limited": "xop",
  "canadian palladium": "bull",
  "canadian palladium resources": "bull",
  "canadian palladium resources inc.": "bull",
  "canadian palladium resources inc. (formerly": "bull",
  "canadian palladium resources inc. (formerly was bull/21c metals inc. until 2020-01-17)": "bull",
  "canafarma": "cnfa",
  "canafarma hemp": "cnfa",
  "canafarma hemp products": "cnfa",
  "canafarma hemp products corp.": "cnfa",
  "canamex": "csq",
  "canamex gold": "csq",
  "canamex gold corp.": "csq",
  "cann": "cann",
  "cann.wt": "cann",
  "cannabis": "cgoc",
  "cannabis growth": "cgoc",
  "cannabis growth opportunity": "cgoc",
  "cannabis growth opportunity corporation": "cgoc",
  "cannabix": "blo",
  "cannabix technologies": "blo",
  "cannabix technologies inc.": "blo",
  "cannamerica": "cana",
  "cannamerica brands": "cana",
  "cannamerica brands corp.": "cana",
  "cannaone": "cnna",
  "cannaone technologies": "cnna",
  "cannaone technologies inc": "cnna",
  "cannara": "love",
  "cannara biotech": "love",
  "cannara biotech inc.": "love",
  "canntab": "pill",
  "canntab therapeutics": "pill",
  "canntab therapeutics limited": "pill",
  "captiva": "pwr",
  "captiva verde": "pwr",
  "captiva verde land": "pwr",
  "captiva verde land corp.": "pwr",
  "captor": "cptr",
  "captor capital": "cptr",
  "captor capital corp": "cptr",
  "carl": "crl",
  "carl data": "crl",
  "carl data solutions": "crl",
  "carl data solutions inc.": "crl",
  "carlyle": "ccc",
  "carlyle commodities": "ccc",
  "carlyle commodities corp.": "ccc",
  "carlyle commodities corp. (formerly": "ccc",
  "carlyle commodities corp. (formerly was": "ccc",
  "carlyle commodities corp. (formerly was dlry/delrey metals corp. until 2020-02-14)": "ccc",
  "cartier": "cfe",
  "cartier iron": "cfe",
  "cartier iron corporation": "cfe",
  "cascadia": "ck",
  "cascadia blockchain": "ck",
  "cascadia blockchain group": "ck",
  "cascadia blockchain group corp.": "ck",
  "cat": "cat",
  "cat strategic": "cat",
  "cat strategic metals": "cat",
  "cat strategic metals corporation": "cat",
  "cb2": "cbii",
  "cb2 insights": "cbii",
  "cb2 insights inc.": "cbii",
  "cbd": "cbdn",
  "cbd global": "cbdn",
  "cbd global sciences": "cbdn",
  "cbd global sciences inc.": "cbdn",
  "cbdn": "cbdn",
  "cbdt": "cbdt",
  "cbii": "cbii",
  "cbk": "cbk",
  "cbp": "cbp",
  "cc": "cc",
  "ccc": "ccc",
  "cchw": "cchw",
  "ccr": "ccr",
  "cdn": "cdn",
  "cdpr": "cdpr",
  "cdva": "cdva",
  "ceg": "ceg",
  "cellcube": "cube",
  "cellcube energy": "cube",
  "cellcube energy storage": "cube",
  "cellcube energy storage systems": "cube",
  "cellcube energy storage systems inc.": "cube",
  "centr": "cntr",
  "centr brands": "cntr",
  "centr brands corp.": "cntr",
  "cerro": "ceg",
  "cerro de": "cdpr",
  "cerro de pasco": "cdpr",
  "cerro de pasco resources": "cdpr",
  "cerro de pasco resources inc.": "cdpr",
  "cerro grande": "ceg",
  "cerro grande mining": "ceg",
  "cerro grande mining corporation": "ceg",
  "certive": "cbp",
  "certive solutions": "cbp",
  "certive solutions inc.": "cbp",
  "cfe": "cfe",
  "cgm": "cgm",
  "cgn": "cgn",
  "cgoc": "cgoc",
  "cgro": "cgro",
  "cgro.wt": "cgro",
  "champignon": "shrm",
  "champignon brands": "shrm",
  "champignon brands inc.": "shrm",
  "chemistree": "chm",
  "chemistree technology": "chm",
  "chemistree technology inc.": "chm",
  "chm": "chm",
  "chm.wt": "chm",
  "choo": "choo",
  "choom": "choo",
  "choom holdings": "choo",
  "choom holdings inc.": "choo",
  "chv": "chv",
  "cielo": "cmc",
  "cielo waste": "cmc",
  "cielo waste solutions": "cmc",
  "cielo waste solutions corp.": "cmc",
  "cig": "cig",
  "cim": "cim",
  "cim international": "cim",
  "cim international group": "cim",
  "cim international group inc.": "cim",
  "citation": "cgro",
  "citation growth": "cgro",
  "citation growth corp.": "cgro",
  "city": "cvgr",
  "city view": "cvgr",
  "city view green": "cvgr",
  "city view green holdings": "cvgr",
  "city view green holdings inc.": "cvgr",
  "ck": "ck",
  "cl": "cl",
  "cl.wt": "cl",
  "clar": "clar",
  "clarity": "clar",
  "clarity gold": "clar",
  "clarity gold corp.": "clar",
  "class": "nico",
  "class 1": "nico",
  "class 1 nickel": "nico",
  "class 1 nickel and": "nico",
  "class 1 nickel and technologies": "nico",
  "class 1 nickel and technologies limited": "nico",
  "cloud": "cni",
  "cloud nine": "cni",
  "cloud nine education": "cni",
  "cloud nine education group": "cni",
  "cloud nine education group ltd.": "cni",
  "cls": "clsh",
  "cls holdings": "clsh",
  "cls holdings usa,": "clsh",
  "cls holdings usa, inc.": "clsh",
  "clsh": "clsh",
  "cmc": "cmc",
  "cme": "cme",
  "cmx": "cxc",
  "cmx gold": "cxc",
  "cmx gold &": "cxc",
  "cmx gold & silver": "cxc",
  "cmx gold & silver corp.": "cxc",
  "cnfa": "cnfa",
  "cni": "cni",
  "cnna": "cnna",
  "cntr": "cntr",
  "co": "co",
  "code": "code",
  "codebase": "code",
  "codebase ventures": "code",
  "codebase ventures inc.": "code",
  "cognetivity": "cgn",
  "cognetivity neurosciences": "cgn",
  "cognetivity neurosciences ltd.": "cgn",
  "columbia": "cchw",
  "columbia care": "cchw",
  "columbia care inc.": "cchw",
  "columbia care inc. (formerly": "cchw",
  "columbia care inc. (formerly was": "cchw",
  "columbia care inc. (formerly was cchw/coumbia care inc. until 2020-03-31)": "cchw",
  "cool": "cool",
  "copperbank": "cbk",
  "copperbank resources": "cbk",
  "copperbank resources corp.": "cbk",
  "cordovacann": "cdva",
  "cordovacann corp.": "cdva",
  "core": "cool",
  "core assets": "cc",
  "core assets corp.": "cc",
  "core one": "cool",
  "core one labs": "cool",
  "core one labs inc.": "cool",
  "corsurex": "crc",
  "corsurex resource": "crc",
  "corsurex resource corp.": "crc",
  "cptr": "cptr",
  "crc": "crc",
  "cres": "cres",
  "cresco": "cl",
  "cresco labs": "cl",
  "cresco labs inc.": "cl",
  "crest": "cres",
  "crest resources": "cres",
  "crest resources inc.": "cres",
  "crestview": "crs",
  "crestview exploration": "crs",
  "crestview exploration inc.": "crs",
  "crft": "crft",
  "crl": "crl",
  "cross": "crvc",
  "cross river": "crvc",
  "cross river ventures": "crvc",
  "cross river ventures corp.": "crvc",
  "crs": "crs",
  "cru": "cru",
  "cruz": "cruz",
  "cruz cobalt": "cruz",
  "cruz cobalt corp.": "cruz",
  "crvc": "crvc",
  "cry": "cry",
  "cryptologic": "cry",
  "cryptologic corp.": "cry",
  "csi.u": "csi",
  "csq": "csq",
  "cube": "cube",
  "cura": "cura",
  "curaleaf": "cura",
  "curaleaf holdings,": "cura",
  "curaleaf holdings, inc.": "cura",
  "cure": "cure",
  "cvgr": "cvgr",
  "cxc": "cxc",
  "cxxi": "cxxi",
  "cyn": "cyn",
  "cyntar": "cyn",
  "cyntar ventures": "cyn",
  "cyntar ventures inc": "cyn",
  "cypherpunk": "hodl",
  "cypherpunk holdings": "hodl",
  "cypherpunk holdings inc.": "hodl",
  "dcsi": "dcsi",
  "ddi": "ddi",
  "debut": "ddi",
  "debut diamonds": "ddi",
  "debut diamonds inc.": "ddi",
  "deep": "deep",
  "deeprock": "deep",
  "deeprock minerals": "deep",
  "deeprock minerals inc.": "deep",
  "deer": "dhc",
  "deer horn": "dhc",
  "deer horn capital": "dhc",
  "deer horn capital inc.": "dhc",
  "deveron": "dvr",
  "deveron uas": "dvr",
  "deveron uas corp.": "dvr",
  "dfly": "dfly",
  "dft": "dft",
  "dhc": "dhc",
  "digi": "digi",
  "digicrypts": "digi",
  "digicrypts blockchain": "digi",
  "digicrypts blockchain solutions": "digi",
  "digicrypts blockchain solutions inc.": "digi",
  "dimension": "dft",
  "dimension five": "dft",
  "dimension five technologies": "dft",
  "dimension five technologies inc.": "dft",
  "direct": "dcsi",
  "direct communication": "dcsi",
  "direct communication solutions": "dcsi",
  "direct communication solutions inc.": "dcsi",
  "dixi.u": "dixi",
  "dni": "dni",
  "dni metals": "dni",
  "dni metals inc.": "dni",
  "doc.wt": "doc",
  "dominion": "dwr",
  "dominion water": "dwr",
  "dominion water reserves": "dwr",
  "dominion water reserves corp.": "dwr",
  "dose": "dose",
  "draganfly": "dfly",
  "draganfly inc.": "dfly",
  "dst": "dst",
  "dundee": "dst",
  "dundee sustainable": "dst",
  "dundee sustainable technologies": "dst",
  "dundee sustainable technologies inc.": "dst",
  "dvr": "dvr",
  "dwr": "dwr",
  "earthrenew": "erth",
  "earthrenew inc.": "erth",
  "easy": "easy",
  "eat": "eat",
  "eco": "eom",
  "eco oro": "eom",
  "eco oro minerals": "eom",
  "eco oro minerals corp.": "eom",
  "eco oro minerals corp. j": "eom",
  "edgemont": "edgm",
  "edgemont gold": "edgm",
  "edgemont gold corp.": "edgm",
  "edgm": "edgm",
  "egf": "tmed",
  "egf theramed": "tmed",
  "egf theramed health": "tmed",
  "egf theramed health corp.": "tmed",
  "egf theramed health corp. (formerly": "tmed",
  "egf theramed health corp. (formerly was tmed/theramed health corporation until 2019-10-23)": "tmed",
  "ehc": "ehc",
  "ei": "ei",
  "emer": "emer",
  "emergia": "emer",
  "emergia inc.": "emer",
  "emergia inc. (formerly": "emer",
  "emergia inc. (formerly was": "emer",
  "emergia inc. (formerly was dlma/the": "emer",
  "emergia inc. (formerly was dlma/the delma group inc. until 2020-01-20)": "emer",
  "empower": "cbdt",
  "empower clinics": "cbdt",
  "empower clinics inc": "cbdt",
  "enviroleach": "eti",
  "enviroleach technologies": "eti",
  "enviroleach technologies inc.": "eti",
  "eom": "eom",
  "epic": "epic",
  "eplay": "epy",
  "eplay digital": "epy",
  "eplay digital inc.": "epy",
  "epy": "epy",
  "erka": "erka",
  "erth": "erth",
  "esi": "opi",
  "esi energy": "opi",
  "esi energy services": "opi",
  "esi energy services inc.": "opi",
  "eti": "eti",
  "etr": "etr",
  "etruscus": "etr",
  "etruscus resources": "etr",
  "etruscus resources corp.": "etr",
  "eureka": "erka",
  "eureka 93": "erka",
  "eureka 93 inc.": "erka",
  "euro": "euro",
  "eurogas": "ei",
  "eurogas international": "ei",
  "eurogas international inc.": "ei",
  "eurolife": "euro",
  "eurolife brands": "euro",
  "eurolife brands inc.": "euro",
  "evg": "evg",
  "eviana": "ehc",
  "eviana health": "ehc",
  "eviana health corporation": "ehc",
  "evolving": "evg",
  "evolving gold": "evg",
  "evolving gold corp.": "evg",
  "exeblock": "xblk",
  "exeblock technology": "xblk",
  "exeblock technology corporation": "xblk",
  "exm": "exm",
  "exmceuticals": "exm",
  "exmceuticals inc.": "exm",
  "exro": "xro",
  "exro technologies": "xro",
  "exro technologies inc.": "xro",
  "fandom": "fdm",
  "fandom sports": "fdm",
  "fandom sports media": "fdm",
  "fandom sports media corp.": "fdm",
  "fans": "fans",
  "fansunite": "fans",
  "fansunite entertainment": "fans",
  "fansunite entertainment inc.": "fans",
  "fansunite entertainment inc. (formerly": "fans",
  "fansunite entertainment inc. (formerly was": "fans",
  "fansunite entertainment inc. (formerly was fans/fansunite entertainment inc until 2020-05-14)": "fans",
  "far": "fat",
  "far resources": "fat",
  "far resources ltd.": "fat",
  "fat": "fat",
  "fdm": "fdm",
  "fe": "fe",
  "fenixoro": "fenx",
  "fenixoro gold": "fenx",
  "fenixoro gold corp.": "fenx",
  "fenx": "fenx",
  "ffnt": "ffnt",
  "fft": "fft",
  "fgfl": "fgfl",
  "fincanna": "cali",
  "fincanna capital": "cali",
  "fincanna capital corp.": "cali",
  "fineqia": "fnq",
  "fineqia international": "fnq",
  "fineqia international inc.": "fnq",
  "fiorentina": "flo",
  "fiorentina minerals": "flo",
  "fiorentina minerals inc.": "flo",
  "first energy": "fe",
  "first energy metals": "fe",
  "first energy metals limited": "fe",
  "first growth": "fgfl",
  "first growth funds": "fgfl",
  "first growth funds limited": "fgfl",
  "first responder": "wpn",
  "first responder technologies": "wpn",
  "first responder technologies inc.": "wpn",
  "flo": "flo",
  "flow": "fwm",
  "flow metals": "fwm",
  "flow metals corp.": "fwm",
  "flower": "fone",
  "flower one": "fone",
  "flower one holdings": "fone",
  "flower one holdings inc.": "fone",
  "flyy": "flyy",
  "fman": "fman",
  "fnau": "fnau",
  "fnq": "fnq",
  "fog": "fog",
  "fogchain": "fog",
  "fogchain corp": "fog",
  "fone": "fone",
  "fone.db": "fone",
  "fone.db.a": "fone",
  "fone.wt": "fone",
  "fone.wt.a": "fone",
  "four": "fnau",
  "four nines": "fnau",
  "four nines gold": "fnau",
  "four nines gold inc.": "fnau",
  "fox": "fox",
  "fox river": "fox",
  "fox river resources": "fox",
  "fox river resources corporation": "fox",
  "freeman": "fman",
  "freeman gold": "fman",
  "freeman gold corp.": "fman",
  "freeman gold corp. (formerly": "fman",
  "freeman gold corp. (formerly was": "fman",
  "freeman gold corp. (formerly was ldg/lodge resources inc. until 2020-05-20)": "fman",
  "fsd": "huge",
  "fsd pharma": "huge",
  "fsd pharma inc.": "huge",
  "fsd pharma inc. subordinate": "huge",
  "fsd pharma inc. subordinate voting": "huge",
  "fsd pharma inc. subordinate voting shares": "huge",
  "futr": "futr",
  "future": "fft",
  "future farm": "fft",
  "future farm technologies": "fft",
  "future farm technologies inc.": "fft",
  "fwm": "fwm",
  "gaby": "gaby",
  "gaby inc.": "gaby",
  "gaby inc. (formerly": "gaby",
  "gaby inc. (formerly was": "gaby",
  "gaby inc. (formerly was gaby/gabriella's": "gaby",
  "gaby inc. (formerly was gaby/gabriella's kitchen inc. until 2019-10-21)": "gaby",
  "gaia": "gaia",
  "gaia grow": "gaia",
  "gaia grow corp.": "gaia",
  "gallagher": "gll",
  "gallagher security": "gll",
  "gallagher security corp.": "gll",
  "gbc": "gbc",
  "gblc": "gblc",
  "gblk": "gblk",
  "gbrx": "gbrx",
  "gca": "gca",
  "gcit": "gcit",
  "gecc": "gecc",
  "gencan": "gca",
  "gencan capital": "gca",
  "gencan capital inc.": "gca",
  "generic": "ggc",
  "generic gold": "ggc",
  "generic gold corp.": "ggc",
  "geni": "geni",
  "genius": "geni",
  "genius metals": "geni",
  "genius metals inc": "geni",
  "getchell": "gtch",
  "getchell gold": "gtch",
  "getchell gold corp.": "gtch",
  "gfi": "gfi",
  "ggb": "ggb",
  "ggb.wt": "ggb",
  "ggc": "ggc",
  "ghg": "ghg",
  "ghg.rt": "ghg",
  "gl": "gl",
  "glh": "glh",
  "gll": "gll",
  "glm": "glm",
  "global": "uav",
  "global cannabis": "app",
  "global cannabis applications": "app",
  "global cannabis applications corp.": "app",
  "global care": "hlth",
  "global care capital": "hlth",
  "global care capital inc.": "hlth",
  "global care capital inc. (formerly": "hlth",
  "global care capital inc. (formerly was rin/resinco capital partners inc. until 2020-04-16)": "hlth",
  "global elsimate": "gecc",
  "global elsimate capital": "gecc",
  "global elsimate capital corp.": "gecc",
  "global elsimate capital corp. (formerly": "gecc",
  "global elsimate capital corp. (formerly was cryp/cryptobloc technologies corp. until 2020-02-05)": "gecc",
  "global health": "mjrx",
  "global health clinics": "mjrx",
  "global health clinics ltd.": "mjrx",
  "global hemp": "ghg",
  "global hemp group": "ghg",
  "global hemp group inc.": "ghg",
  "global li-ion": "lion",
  "global li-ion graphite": "lion",
  "global li-ion graphite corp.": "lion",
  "global uav": "uav",
  "global uav technologies": "uav",
  "global uav technologies ltd.": "uav",
  "globex": "swis",
  "globex data": "swis",
  "globex data ltd.": "swis",
  "glorious": "gcit",
  "glorious creation": "gcit",
  "glorious creation limited": "gcit",
  "go metals": "goco",
  "go metals corp": "goco",
  "goco": "goco",
  "goh": "goh",
  "gold": "gpmi",
  "gold lion": "gl",
  "gold lion resources": "gl",
  "gold lion resources inc.": "gl",
  "gold plus": "gpmi",
  "gold plus mining": "gpmi",
  "gold plus mining inc.": "gpmi",
  "gold plus mining inc. (formerly": "gpmi",
  "gold plus mining inc. (formerly was sydf/syd financial inc. until 2020-03-03)": "gpmi",
  "gold'futures": "futr",
  "gold'futures mineral": "futr",
  "gold'futures mineral corp.": "futr",
  "goldblock": "gblk",
  "goldblock capital": "gblk",
  "goldblock capital inc.": "gblk",
  "golden": "glh",
  "golden birch": "gbrx",
  "golden birch resources": "gbrx",
  "golden birch resources inc.": "gbrx",
  "golden lake": "glm",
  "golden lake exploration": "glm",
  "golden lake exploration inc.": "glm",
  "golden leaf": "glh",
  "golden leaf holdings": "glh",
  "golden leaf holdings ltd.": "glh",
  "goldhaven": "goh",
  "goldhaven resources": "goh",
  "goldhaven resources corp.": "goh",
  "goldhaven resources corp. (formerly": "goh",
  "goldhaven resources corp. (formerly was": "goh",
  "goldhaven resources corp. (formerly was altm/altum resource corp. until 2020-07-02)": "goh",
  "goldrea": "gor",
  "goldrea resources": "gor",
  "goldrea resources corp.": "gor",
  "goldseek": "gsk",
  "goldseek resources": "gsk",
  "goldseek resources inc.": "gsk",
  "gor": "gor",
  "gpk": "gpk",
  "gpmi": "gpmi",
  "grand": "gpk",
  "grand peak": "gpk",
  "grand peak capital": "gpk",
  "grand peak capital corp.": "gpk",
  "graph": "gblc",
  "graph blockchain": "gblc",
  "graph blockchain inc": "gblc",
  "gravitas": "gfi",
  "gravitas financial": "gfi",
  "gravitas financial inc.": "gfi",
  "gray": "gray",
  "graycliff": "gray",
  "graycliff exploration": "gray",
  "graycliff exploration limited": "gray",
  "gre.x": "gre",
  "great": "gtg",
  "great thunder": "gtg",
  "great thunder gold": "gtg",
  "great thunder gold corp.": "gtg",
  "green": "gtii",
  "green 2": "gtbe",
  "green 2 blue": "gtbe",
  "green 2 blue energy": "gtbe",
  "green 2 blue energy corp.": "gtbe",
  "green growth": "ggb",
  "green growth brands": "ggb",
  "green growth brands inc.": "ggb",
  "green river": "ccr",
  "green river gold": "ccr",
  "green river gold corp.": "ccr",
  "green thumb": "gtii",
  "green thumb industries": "gtii",
  "green thumb industries inc.": "gtii",
  "greenbank": "gbc",
  "greenbank capital": "gbc",
  "greenbank capital inc.": "gbc",
  "greenstar": "gstr",
  "greenstar biosciences": "gstr",
  "greenstar biosciences corp.": "gstr",
  "grin": "grin",
  "grown": "grin",
  "grown rogue": "grin",
  "grown rogue international": "grin",
  "grown rogue international inc.": "grin",
  "gsk": "gsk",
  "gstr": "gstr",
  "gtbe": "gtbe",
  "gtch": "gtch",
  "gtg": "gtg",
  "gti.x": "gti",
  "gtii": "gtii",
  "harborside": "hbor",
  "harborside inc.": "hbor",
  "harrys": "hary",
  "harrys manufacturing": "hary",
  "harrys manufacturing inc.": "hary",
  "harv": "harv",
  "harvest": "harv",
  "harvest health": "harv",
  "harvest health &": "harv",
  "harvest health & recreation": "harv",
  "harvest health & recreation inc.": "harv",
  "hary": "hary",
  "hbor": "hbor",
  "healthspace": "hs",
  "healthspace data": "hs",
  "healthspace data systems": "hs",
  "healthspace data systems ltd.": "hs",
  "hello": "hp",
  "hello pal": "hp",
  "hello pal international": "hp",
  "hello pal international inc.": "hp",
  "hemp": "hfh",
  "hemp for": "hfh",
  "hemp for health": "hfh",
  "hemp for health inc.": "hfh",
  "heritage": "hgp",
  "heritage cannabis": "cann",
  "heritage cannabis holdings": "cann",
  "heritage cannabis holdings corp.": "cann",
  "heritage global": "hgp",
  "heritage global inc.": "hgp",
  "hey": "hey",
  "heybryan": "hey",
  "heybryan media": "hey",
  "heybryan media inc.": "hey",
  "hfh": "hfh",
  "hgh": "hgh",
  "hgp": "hgp",
  "hhs": "hhs",
  "hi": "hhs",
  "hi ho": "hhs",
  "hi ho silver": "hhs",
  "hi ho silver resources": "hhs",
  "hi ho silver resources inc.": "hhs",
  "high": "hiti",
  "high point": "hgh",
  "high point exploration": "hgh",
  "high point exploration inc.": "hgh",
  "high tide": "hiti",
  "high tide inc.": "hiti",
  "hiti": "hiti",
  "hlth": "hlth",
  "hodl": "hodl",
  "holl": "holl",
  "hollister": "holl",
  "hollister biosciences": "holl",
  "hollister biosciences inc.": "holl",
  "hp": "hp",
  "hs": "hs",
  "huge": "huge",
  "hydro66": "six",
  "hydro66 holdings": "six",
  "hydro66 holdings corp.": "six",
  "hyperblock": "hypr",
  "hyperblock inc.": "hypr",
  "hypr": "hypr",
  "i3": "bets",
  "i3 interactive": "bets",
  "i3 interactive inc.": "bets",
  "ian": "ian",
  "ianthus": "ian",
  "ianthus capital": "ian",
  "ianthus capital holdings": "ian",
  "ianthus capital holdings inc.": "ian",
  "ibat": "ibat",
  "ic": "ic",
  "ic capitalight": "ic",
  "ic capitalight corp.": "ic",
  "ican": "ican",
  "icanic": "ican",
  "icanic brands": "ican",
  "icanic brands company": "ican",
  "icanic brands company inc": "ican",
  "icanic brands company inc (formerly": "ican",
  "icanic brands company inc (formerly was ican/integrated cannabis company inc. until 2020-02-14)": "ican",
  "icesoft": "isft",
  "icesoft technologies": "isft",
  "icesoft technologies canada": "isft",
  "icesoft technologies canada corp.": "isft",
  "idaho": "itko",
  "idaho champion": "itko",
  "idaho champion gold": "itko",
  "idaho champion gold mines": "itko",
  "idaho champion gold mines canada": "itko",
  "idaho champion gold mines canada inc.": "itko",
  "idk": "idk",
  "idvr": "idvr",
  "igen": "ign",
  "igen networks": "ign",
  "igen networks corp.": "ign",
  "ign": "ign",
  "ignite": "bilz",
  "ignite international": "bilz",
  "ignite international brands,": "bilz",
  "ignite international brands, ltd.s.v.": "bilz",
  "im": "im",
  "im cannabis": "imcc",
  "im cannabis corp.": "imcc",
  "im exploration": "im",
  "im exploration inc.": "im",
  "imagin": "ime",
  "imagin medical": "ime",
  "imagin medical inc.": "ime",
  "imaginear": "ip",
  "imaginear inc.": "ip",
  "imaginear inc. (formerly": "ip",
  "imaginear inc. (formerly was": "ip",
  "imaginear inc. (formerly was ip/imagination": "ip",
  "imaginear inc. (formerly was ip/imagination park technologies until 2020-04-15)": "ip",
  "imc": "imcx",
  "imc international": "imcx",
  "imc international mining": "imcx",
  "imc international mining corp.": "imcx",
  "imcc": "imcc",
  "imcc.wt": "imcc",
  "imcx": "imcx",
  "ime": "ime",
  "inds": "inds",
  "indus": "inds",
  "indus holdings,": "inds",
  "indus holdings, inc.": "inds",
  "indvr": "idvr",
  "indvr brands": "idvr",
  "indvr brands inc.": "idvr",
  "indvr brands inc. (formerly": "idvr",
  "indvr brands inc. (formerly was": "idvr",
  "indvr brands inc. (formerly was cbis/cannabis one holdings inc. until 2020-08-18)": "idvr",
  "inflection": "aucu",
  "inflection resources": "aucu",
  "inflection resources ltd.": "aucu",
  "inner": "ish",
  "inner spirit": "ish",
  "inner spirit holdings": "ish",
  "inner spirit holdings ltd.": "ish",
  "inno": "inno",
  "innocan": "inno",
  "innocan pharma": "inno",
  "innocan pharma corporation": "inno",
  "inspiration": "ism",
  "inspiration mining": "ism",
  "inspiration mining corporation": "ism",
  "intellabridge": "intl",
  "intellabridge technology": "intl",
  "intellabridge technology corporation": "intl",
  "intellabridge technology corporation (formerly": "intl",
  "intellabridge technology corporation (formerly was": "intl",
  "intellabridge technology corporation (formerly was nite/cryptanite blockchain technologies corp. until 2019-10-23)": "intl",
  "international": "co",
  "international battery": "ibat",
  "international battery metals": "ibat",
  "international battery metals ltd.": "ibat",
  "international cobalt": "co",
  "international cobalt corp": "co",
  "intl": "intl",
  "ionc": "ionc",
  "ionic": "ionc",
  "ionic brands": "ionc",
  "ionic brands corp.": "ionc",
  "ip": "ip",
  "ipot": "ipot",
  "irv": "irv",
  "irving": "irv",
  "irving resources": "irv",
  "irving resources inc.": "irv",
  "isft": "isft",
  "ish": "ish",
  "ish.db": "ish",
  "ish.wt": "ish",
  "ism": "ism",
  "isodiol": "isol",
  "isodiol international": "isol",
  "isodiol international inc.": "isol",
  "isol": "isol",
  "isracann": "ipot",
  "isracann biosciences": "ipot",
  "isracann biosciences inc.": "ipot",
  "itko": "itko",
  "ivor": "ivor",
  "ivor exploration": "ivor",
  "ivor exploration inc.": "ivor",
  "izo": "izo",
  "izotropic": "izo",
  "izotropic corporation": "izo",
  "j": "j",
  "james": "jbr",
  "james bay": "jbr",
  "james bay resources": "jbr",
  "james bay resources limited": "jbr",
  "jane": "jane",
  "jbr": "jbr",
  "jdf": "jdf",
  "jdf explorations": "jdf",
  "jdf explorations inc.": "jdf",
  "jjj.x": "jjj",
  "jnc": "jnc",
  "jnc resources": "jnc",
  "jnc resources inc.": "jnc",
  "jq": "jq",
  "jush": "jush",
  "jushi": "jush",
  "jushi holdings": "jush",
  "jushi holdings inc.": "jush",
  "jushi holdings inc. class": "jush",
  "jushi holdings inc. class b": "jush",
  "jushi holdings inc. class b subordinate voting shares": "jush",
  "kabn": "kabn",
  "kabn systems": "kabn",
  "kabn systems na": "kabn",
  "kabn systems na holdings": "kabn",
  "kabn systems na holdings corp.": "kabn",
  "karam": "kmi",
  "karam minerals": "kmi",
  "karam minerals inc.": "kmi",
  "kbev": "kbev",
  "kdz.x": "kdz",
  "kmi": "kmi",
  "knr": "knr",
  "koios": "kbev",
  "koios beverage": "kbev",
  "koios beverage corp.": "kbev",
  "kontrol": "knr",
  "kontrol energy": "knr",
  "kontrol energy corp.": "knr",
  "kootenay": "znk",
  "kootenay zinc": "znk",
  "kootenay zinc corp.": "znk",
  "kwg": "kwg",
  "kwg resources": "kwg",
  "kwg resources inc.": "kwg",
  "kwg.a": "kwg",
  "la": "lai",
  "la imperial": "lai",
  "la imperial resources": "lai",
  "la imperial resources inc.": "lai",
  "lai": "lai",
  "lanebury": "lll",
  "lanebury growth": "lll",
  "lanebury growth capital": "lll",
  "lanebury growth capital ltd.": "lll",
  "lbm": "lbm",
  "leanlife": "llp",
  "leanlife health": "llp",
  "leanlife health inc.": "llp",
  "lecr": "lecr",
  "leocor": "lecr",
  "leocor gold": "lecr",
  "leocor gold inc.": "lecr",
  "leocor gold inc. (formerly": "lecr",
  "leocor gold inc. (formerly was": "lecr",
  "leocor gold inc. (formerly was lecr/leocor ventures inc until 2020-08-04)": "lecr",
  "leviathan": "epic",
  "leviathan natural": "epic",
  "leviathan natural products": "epic",
  "leviathan natural products inc.": "epic",
  "leviathan natural products inc. (formerly": "epic",
  "leviathan natural products inc. (formerly was epic/leviathan cannabis group inc. until 2020-07-20)": "epic",
  "lexaria": "lxx",
  "lexaria bioscience": "lxx",
  "lexaria bioscience corp.": "lxx",
  "lhs": "lhs",
  "liberty": "lhs",
  "liberty health": "lhs",
  "liberty health sciences": "lhs",
  "liberty health sciences inc.": "lhs",
  "lida": "lida",
  "lida resources": "lida",
  "lida resources inc.": "lida",
  "lida resources inc. (formerly": "lida",
  "lida resources inc. (formerly was": "lida",
  "lida resources inc. (formerly was lid/lida resources inc. until 2020-06-03)": "lida",
  "lido": "lido",
  "lido minerals": "lido",
  "lido minerals ltd.": "lido",
  "lily": "lily",
  "link": "lnk",
  "link global": "lnk",
  "link global technologies": "lnk",
  "link global technologies inc.": "lnk",
  "lion": "lion",
  "lions": "lbm",
  "lions bay": "lbm",
  "lions bay mining": "lbm",
  "lions bay mining corp.": "lbm",
  "litelink": "llt",
  "litelink technologies": "llt",
  "litelink technologies inc.": "llt",
  "lll": "lll",
  "llp": "llp",
  "llt": "llt",
  "lnk": "lnk",
  "loan": "loan",
  "lotus": "j",
  "lotus ventures": "j",
  "lotus ventures inc.": "j",
  "love": "love",
  "luff": "luff",
  "luff enterprises": "luff",
  "luff enterprises ltd.": "luff",
  "luff enterprises ltd. (formerly": "luff",
  "luff enterprises ltd. (formerly was": "luff",
  "luff enterprises ltd. (formerly was asnt/ascent industries corp. until 2020-05-19)": "luff",
  "lux": "lux",
  "luxx": "luxx",
  "luxxfolio": "luxx",
  "luxxfolio holdings": "luxx",
  "luxxfolio holdings inc.": "luxx",
  "lxx": "lxx",
  "mag": "mdd",
  "mag one": "mdd",
  "mag one products": "mdd",
  "mag one products inc.": "mdd",
  "major": "size",
  "major precious": "size",
  "major precious metals": "size",
  "major precious metals corp.": "size",
  "major precious metals corp. (formerly": "size",
  "major precious metals corp. (formerly was eznc/eastern zinc corp. until 2020-06-19)": "size",
  "maka": "maka",
  "makara": "maka",
  "makara mining": "maka",
  "makara mining corp.": "maka",
  "mann": "mann",
  "manning": "mann",
  "manning ventures": "mann",
  "manning ventures inc.": "mann",
  "marble": "mrbl",
  "marble financial": "mrbl",
  "marble financial inc.": "mrbl",
  "marble financial inc. (formerly": "mrbl",
  "marble financial inc. (formerly was": "mrbl",
  "marble financial inc. (formerly was mrbl/mli marble lending inc. until 2019-11-18)": "mrbl",
  "mariner": "rnr",
  "mariner resources": "rnr",
  "mariner resources corp.": "rnr",
  "matica": "mmj",
  "matica enterprises": "mmj",
  "matica enterprises inc.": "mmj",
  "maxtech": "mvt",
  "maxtech ventures": "mvt",
  "maxtech ventures inc.": "mvt",
  "mcl": "mcl",
  "mclaren": "mcl",
  "mclaren resources": "mcl",
  "mclaren resources inc.": "mcl",
  "mdd": "mdd",
  "me": "mec",
  "me resource": "mec",
  "me resource corp.": "mec",
  "meat": "meat",
  "mec": "mec",
  "media": "flyy",
  "media central": "flyy",
  "media central corporation": "flyy",
  "media central corporation inc": "flyy",
  "medmen": "mmen",
  "medmen enterprises": "mmen",
  "medmen enterprises inc.": "mmen",
  "medmen enterprises inc. class": "mmen",
  "medmen enterprises inc. class b": "mmen",
  "medmen enterprises inc. class b subordinate voting shares": "mmen",
  "medxtractor": "mxt",
  "medxtractor corp.": "mxt",
  "megumagold": "nsau",
  "megumagold corp": "nsau",
  "metalo": "mmi",
  "metalo manufacturing": "mmi",
  "metalo manufacturing inc.": "mmi",
  "metamaterial": "mmat",
  "metamaterial inc.": "mmat",
  "mgro": "mgro",
  "mgx": "xmg",
  "mgx minerals": "xmg",
  "mgx minerals inc.": "xmg",
  "mhy.un": "mhy",
  "mich": "mich",
  "mich resources": "mich",
  "mich resources ltd": "mich",
  "mich resources ltd (formerly": "mich",
  "mich resources ltd (formerly was": "mich",
  "mich resources ltd (formerly was mich/michelin mining corp. until 2019-12-03)": "mich",
  "micromem": "mrm",
  "micromem technologies": "mrm",
  "micromem technologies inc.": "mrm",
  "micron": "mwm",
  "micron waste": "mwm",
  "micron waste technologies": "mwm",
  "micron waste technologies inc": "mwm",
  "minera": "mirl",
  "minera irl": "mirl",
  "minera irl limited": "mirl",
  "miramont": "mont",
  "miramont resources": "mont",
  "miramont resources corp.": "mont",
  "mirl": "mirl",
  "mis": "mis",
  "mistango": "mis",
  "mistango river": "mis",
  "mistango river resources": "mis",
  "mistango river resources inc.": "mis",
  "mj": "mj",
  "mjar": "mjar",
  "mjardin": "mjar",
  "mjardin group,": "mjar",
  "mjardin group, inc.": "mjar",
  "mjrx": "mjrx",
  "mmat": "mmat",
  "mmc": "mmc",
  "mmen": "mmen",
  "mmen.wt": "mmen",
  "mmf.un": "mmf",
  "mmi": "mmi",
  "mmj": "mmj",
  "mng": "mng",
  "modern": "meat",
  "modern meat": "meat",
  "modern meat inc.": "meat",
  "mojave": "jane",
  "mojave jane": "jane",
  "mojave jane brands": "jane",
  "mojave jane brands inc.": "jane",
  "mongoose": "mng",
  "mongoose mining": "mng",
  "mongoose mining ltd.": "mng",
  "mont": "mont",
  "monterey": "mrey",
  "monterey minerals": "mrey",
  "monterey minerals inc.": "mrey",
  "mountain": "mvmd",
  "mountain valley": "mvmd",
  "mountain valley md": "mvmd",
  "mountain valley md holdings": "mvmd",
  "mountain valley md holdings inc.": "mvmd",
  "mpv": "mpv",
  "mpv exploration": "mpv",
  "mpv exploration inc": "mpv",
  "mpx": "mpxi",
  "mpx international": "mpxi",
  "mpx international corporation": "mpxi",
  "mpxi": "mpxi",
  "mrbl": "mrbl",
  "mrey": "mrey",
  "mrm": "mrm",
  "mustgrow": "mgro",
  "mustgrow biologics": "mgro",
  "mustgrow biologics corp.": "mgro",
  "mvmd": "mvmd",
  "mvt": "mvt",
  "mwm": "mwm",
  "mxt": "mxt",
  "my.x": "my",
  "myco": "myco",
  "mydecine": "myco",
  "mydecine innovations": "myco",
  "mydecine innovations group": "myco",
  "mydecine innovations group inc.": "myco",
  "mydecine innovations group inc. (formerly": "myco",
  "mydecine innovations group inc. (formerly was nlb/newleaf brands inc. until 2020-06-04)": "myco",
  "mym": "mym",
  "mym nutraceuticals": "mym",
  "mym nutraceuticals inc.": "mym",
  "myr.x": "myr",
  "myriad": "mmc",
  "myriad metals": "mmc",
  "myriad metals corp.": "mmc",
  "nab": "nab",
  "nab.db": "nab",
  "nab.wt": "nab",
  "nabis": "nab",
  "nabis holdings": "nab",
  "nabis holdings inc.": "nab",
  "namesilo": "url",
  "namesilo technologies": "url",
  "namesilo technologies corp.": "url",
  "nanosphere": "nshs",
  "nanosphere health": "nshs",
  "nanosphere health sciences": "nshs",
  "nanosphere health sciences inc.": "nshs",
  "nass": "nvg",
  "nass valley": "nvg",
  "nass valley gateway": "nvg",
  "nass valley gateway ltd.": "nvg",
  "nbud": "nbud",
  "nc": "nc",
  "nerd": "nerd",
  "nerds": "nerd",
  "nerds on": "nerd",
  "nerds on site": "nerd",
  "nerds on site inc.": "nerd",
  "netc.x": "netc",
  "netcents": "nc",
  "netcents technology": "nc",
  "netcents technology inc.": "nc",
  "new": "spor",
  "new leaf": "nlv",
  "new leaf ventures": "nlv",
  "new leaf ventures inc.": "nlv",
  "new tech": "ntm",
  "new tech minerals": "ntm",
  "new tech minerals corp.": "ntm",
  "new wave": "spor",
  "new wave holdings": "spor",
  "new wave holdings corp.": "spor",
  "new wave holdings corp. (formerly": "spor",
  "new wave holdings corp. (formerly was nwes/new wave esports corp. until 2020-05-07)": "spor",
  "newlox": "lux",
  "newlox gold": "lux",
  "newlox gold ventures": "lux",
  "newlox gold ventures corp.": "lux",
  "nexco": "nxu",
  "nexco resources": "nxu",
  "nexco resources inc.": "nxu",
  "next": "ngw",
  "next green": "ngw",
  "next green wave": "ngw",
  "next green wave holdings": "ngw",
  "next green wave holdings inc.": "ngw",
  "nextech": "ntar",
  "nextech ar": "ntar",
  "nextech ar solutions": "ntar",
  "nextech ar solutions corp": "ntar",
  "nextleaf": "oils",
  "nextleaf solutions": "oils",
  "nextleaf solutions ltd.": "oils",
  "ngw": "ngw",
  "nhs": "nhs",
  "nhs industries": "nhs",
  "nhs industries ltd.": "nhs",
  "ni": "ni",
  "nico": "nico",
  "nlr": "nlr",
  "nlv": "nlv",
  "nom": "nom",
  "norsemont": "nom",
  "norsemont mining": "nom",
  "norsemont mining inc.": "nom",
  "norsemont mining inc. (formerly": "nom",
  "norsemont mining inc. (formerly was": "nom",
  "norsemont mining inc. (formerly was nom/norsemont capital inc. until 2020-02-21)": "nom",
  "north": "nbud",
  "north bud": "nbud",
  "north bud farms": "nbud",
  "north bud farms inc.": "nbud",
  "northern": "nlr",
  "northern lights": "nlr",
  "northern lights resources": "nlr",
  "northern lights resources corp.": "nlr",
  "northstar": "nsg",
  "northstar gold": "nsg",
  "northstar gold corp.": "nsg",
  "nova": "nova",
  "nova mentis": "nova",
  "nova mentis life": "nova",
  "nova mentis life sciences": "nova",
  "nova mentis life sciences corp.": "nova",
  "nova mentis life sciences corp. (formerly was lib/liberty leaf holdings ltd. until 2020-06-25)": "nova",
  "npt": "npt",
  "nsau": "nsau",
  "nsg": "nsg",
  "nshs": "nshs",
  "ntar": "ntar",
  "ntm": "ntm",
  "nugt": "nugt",
  "nuinsco": "nwi",
  "nuinsco resources": "nwi",
  "nuinsco resources limited": "nwi",
  "nur": "nur",
  "nuran": "nur",
  "nuran wireless": "nur",
  "nuran wireless inc.": "nur",
  "nutritional": "eat",
  "nutritional high": "eat",
  "nutritional high international": "eat",
  "nutritional high international inc.": "eat",
  "nvg": "nvg",
  "nwi": "nwi",
  "nxu": "nxu",
  "oakley": "oaky",
  "oakley ventures": "oaky",
  "oakley ventures inc.": "oaky",
  "oaky": "oaky",
  "oil": "oil",
  "oils": "oils",
  "one world": "owli",
  "one world lithium": "owli",
  "one world lithium inc.": "owli",
  "opc": "opc",
  "opi": "opi",
  "orcd": "orcd",
  "orchid": "orcd",
  "orchid ventures": "orcd",
  "orchid ventures inc.": "orcd",
  "organic": "opc",
  "organic flower": "sow",
  "organic flower investments": "sow",
  "organic flower investments group": "sow",
  "organic flower investments group inc.": "sow",
  "organic potash": "opc",
  "organic potash corporation": "opc",
  "orgn": "orgn",
  "ori": "ori",
  "origen": "orgn",
  "origen resources": "orgn",
  "origen resources inc.": "orgn",
  "orion": "ori",
  "orion nutraceuticals": "ori",
  "orion nutraceuticals inc.": "ori",
  "orth": "orth",
  "ortho": "orth",
  "ortho regenerative": "orth",
  "ortho regenerative technologies": "orth",
  "ortho regenerative technologies inc.": "orth",
  "oso": "oso",
  "osoyoos": "oso",
  "osoyoos cannabis": "oso",
  "osoyoos cannabis inc.": "oso",
  "ovat": "ovat",
  "ovation": "ovat",
  "ovation science": "ovat",
  "ovation science inc": "ovat",
  "owli": "owli",
  "pac": "pacr",
  "pac roots": "pacr",
  "pac roots cannabis": "pacr",
  "pac roots cannabis corp.": "pacr",
  "pacr": "pacr",
  "paid": "paid",
  "parcelpal": "pkg",
  "parcelpal technology": "pkg",
  "parcelpal technology inc.": "pkg",
  "pasinex": "pse",
  "pasinex resources": "pse",
  "pasinex resources limited": "pse",
  "patriot": "pgol",
  "patriot gold": "pgol",
  "patriot gold corp.": "pgol",
  "pau": "pau",
  "pbit": "pbit",
  "pbt.u": "pbt",
  "pdo": "pdo",
  "pdti": "pdti",
  "peak": "pkk",
  "peak positioning": "pkk",
  "peak positioning technologies": "pkk",
  "peak positioning technologies inc.": "pkk",
  "peekaboo": "bean",
  "peekaboo beans": "bean",
  "peekaboo beans inc": "bean",
  "peloton": "pmc",
  "peloton minerals": "pmc",
  "peloton minerals corporation": "pmc",
  "perk": "perk",
  "perk labs": "perk",
  "perk labs inc.": "perk",
  "perk labs inc. (formerly": "perk",
  "perk labs inc. (formerly was": "perk",
  "perk labs inc. (formerly was get/glance technologies inc. until 2020-02-24)": "perk",
  "permex": "oil",
  "permex petroleum": "oil",
  "permex petroleum corporation": "oil",
  "pgol": "pgol",
  "pharmadrug": "buzz",
  "pharmadrug inc.": "buzz",
  "pharmadrug inc. (formerly": "buzz",
  "pharmadrug inc. (formerly was": "buzz",
  "pharmadrug inc. (formerly was buzz/aura": "buzz",
  "pharmadrug inc. (formerly was buzz/aura health inc. until 2019-10-21)": "buzz",
  "phivida": "vida",
  "phivida holdings": "vida",
  "phivida holdings inc.": "vida",
  "pill": "pill",
  "pjo": "pjo",
  "pkg": "pkg",
  "pkk": "pkk",
  "plaintree": "npt",
  "plaintree systems": "npt",
  "plaintree systems inc.": "npt",
  "planet": "plth",
  "planet 13": "plth",
  "planet 13 holdings": "plth",
  "planet 13 holdings inc.": "plth",
  "platinex": "ptx",
  "platinex inc.": "ptx",
  "play": "play",
  "plnt": "plnt",
  "plth": "plth",
  "plth.wt": "plth",
  "plth.wt.a": "plth",
  "plus": "plus",
  "plus products": "plus",
  "plus products inc": "plus",
  "plus.db": "plus",
  "plus.wt": "plus",
  "plymouth": "prt",
  "plymouth rock": "prt",
  "plymouth rock technologies": "prt",
  "plymouth rock technologies inc.": "prt",
  "pmc": "pmc",
  "pmed": "pmed",
  "posabit": "pbit",
  "posabit systems": "pbit",
  "posabit systems corporation": "pbit",
  "pot": "pot",
  "predictmedix": "pmed",
  "predictmedix inc.": "pmed",
  "predictmedix inc. (formerly": "pmed",
  "predictmedix inc. (formerly was": "pmed",
  "predictmedix inc. (formerly was cult/cultivar": "pmed",
  "predictmedix inc. (formerly was cult/cultivar holdings inc. until 2020-04-08)": "pmed",
  "preferred": "pdti",
  "preferred dental": "pdti",
  "preferred dental technologies": "pdti",
  "preferred dental technologies inc.": "pdti",
  "prev": "prev",
  "preveceutical": "prev",
  "preveceutical medical": "prev",
  "preveceutical medical inc.": "prev",
  "primo": "prmo",
  "primo nutraceuticals": "prmo",
  "primo nutraceuticals inc": "prmo",
  "prmo": "prmo",
  "project": "pjo",
  "project one": "pjo",
  "project one resources": "pjo",
  "project one resources ltd.": "pjo",
  "prophecy": "nugt",
  "prophecy potash": "nugt",
  "prophecy potash corp.": "nugt",
  "provenance": "pau",
  "provenance gold": "pau",
  "provenance gold corp.": "pau",
  "prt": "prt",
  "pse": "pse",
  "ptx": "ptx",
  "pudo": "pdo",
  "pudo inc.": "pdo",
  "pump": "pump",
  "push": "push",
  "pushfor": "push",
  "pushfor investments": "push",
  "pushfor investments inc.": "push",
  "pwr": "pwr",
  "qbot": "qbot",
  "qca": "qca",
  "qq": "qq",
  "qsc": "qsc",
  "quantum": "qbot",
  "quantum cobalt": "qbot",
  "quantum cobalt corp": "qbot",
  "questcap": "qsc",
  "questcap inc.": "qsc",
  "questcap inc. (formerly": "qsc",
  "questcap inc. (formerly was": "qsc",
  "questcap inc. (formerly was qsc/copper": "qsc",
  "questcap inc. (formerly was qsc/copper one inc. until 2019-09-27)": "qsc",
  "quinsam": "qca",
  "quinsam capital": "qca",
  "quinsam capital corporation": "qca",
  "quizam": "qq",
  "quizam media": "qq",
  "quizam media corporation": "qq",
  "rad": "rad",
  "radial": "rad",
  "radial research": "rad",
  "radial research corp": "rad",
  "radiko": "rdko",
  "radiko holdings": "rdko",
  "radiko holdings corp.": "rdko",
  "radiko holdings corp. (formerly": "rdko",
  "radiko holdings corp. (formerly was": "rdko",
  "radiko holdings corp. (formerly was rdko/international cannabrands inc. until 2020-07-23)": "rdko",
  "raffles": "rich",
  "raffles financial": "rich",
  "raffles financial group": "rich",
  "raffles financial group limited": "rich",
  "rain": "rain",
  "rain city": "rain",
  "rain city resources": "rain",
  "rain city resources inc.": "rain",
  "raindrop": "rayn",
  "raindrop ventures": "rayn",
  "raindrop ventures inc.": "rayn",
  "ramm": "ramm",
  "ramm pharma": "ramm",
  "ramm pharma corp.": "ramm",
  "rapid": "dose",
  "rapid dose": "dose",
  "rapid dose therapeutics": "dose",
  "rapid dose therapeutics corp.": "dose",
  "ravenquest": "rqb",
  "ravenquest biomed": "rqb",
  "ravenquest biomed inc.": "rqb",
  "rayn": "rayn",
  "razore": "rzr",
  "razore rock": "rzr",
  "razore rock resources": "rzr",
  "razore rock resources inc.": "rzr",
  "rclf": "rclf",
  "rdko": "rdko",
  "red": "rwb",
  "red lake": "rgld",
  "red lake gold": "rgld",
  "red lake gold inc.": "rgld",
  "red light": "trip",
  "red light holland": "trip",
  "red light holland corp.": "trip",
  "red white": "rwb",
  "red white &": "rwb",
  "red white & bloom": "rwb",
  "red white & bloom brands": "rwb",
  "red white & bloom brands inc.": "rwb",
  "redfund": "loan",
  "redfund capital": "loan",
  "redfund capital corp.": "loan",
  "rela": "rela",
  "relay": "rela",
  "relay medical": "rela",
  "relay medical corp.": "rela",
  "reliant": "rng",
  "reliant gold": "rng",
  "reliant gold corp.": "rng",
  "renforth": "rfr",
  "renforth resources": "rfr",
  "renforth resources inc.": "rfr",
  "reo": "reo",
  "reservoir": "reo",
  "reservoir capital": "reo",
  "reservoir capital corp.": "reo",
  "revive": "rvv",
  "revive therapeutics": "rvv",
  "revive therapeutics ltd.": "rvv",
  "rfr": "rfr",
  "rgld": "rgld",
  "rgo.x": "rgo",
  "rich": "rich",
  "rift": "rvr",
  "rift valley": "rvr",
  "rift valley resources": "rvr",
  "rift valley resources corp.": "rvr",
  "rise": "rlsc",
  "rise gold": "rise",
  "rise gold corp.": "rise",
  "rise life": "rlsc",
  "rise life science": "rlsc",
  "rise life science corp.": "rlsc",
  "rks": "rks",
  "rlg": "rlg",
  "rlsc": "rlsc",
  "rmmi": "rmmi",
  "rmmi corp.": "rmmi",
  "rng": "rng",
  "rnr": "rnr",
  "rockcliff": "rclf",
  "rockcliff metals": "rclf",
  "rockcliff metals corporation": "rclf",
  "rockex": "rxm",
  "rockex mining": "rxm",
  "rockex mining corporation": "rxm",
  "rockshield": "rks",
  "rockshield capital": "rks",
  "rockshield capital corp.": "rks",
  "romj": "romj",
  "romj.wt": "romj",
  "rqb": "rqb",
  "rubicon": "romj",
  "rubicon organics": "romj",
  "rubicon organics inc.": "romj",
  "rvr": "rvr",
  "rvv": "rvv",
  "rwb": "rwb",
  "rxm": "rxm",
  "rzr": "rzr",
  "safe": "safe",
  "sand": "sand",
  "sassy": "sasy",
  "sassy resources": "sasy",
  "sassy resources corporation": "sasy",
  "sasy": "sasy",
  "sbd": "sbd",
  "sbd capital": "sbd",
  "sbd capital corp.": "sbd",
  "scotch": "scv",
  "scotch creek": "scv",
  "scotch creek ventures": "scv",
  "scotch creek ventures inc.": "scv",
  "scv": "scv",
  "se": "se",
  "seahawk": "shv",
  "seahawk ventures": "shv",
  "seahawk ventures inc.": "shv",
  "sens": "sens",
  "sensor": "sens",
  "sensor technologies": "sens",
  "sensor technologies corp": "sens",
  "sensor technologies corp (formerly": "sens",
  "sensor technologies corp (formerly was": "sens",
  "sensor technologies corp (formerly was sens/sensor technologies inc. until 2020-01-27)": "sens",
  "sentinel": "snl",
  "sentinel resources": "snl",
  "sentinel resources corp.": "snl",
  "sg": "sg",
  "sgro": "sgro",
  "sharc": "shrc",
  "sharc international": "shrc",
  "sharc international systems": "shrc",
  "sharc international systems inc.": "shrc",
  "shoal": "shp",
  "shoal point": "shp",
  "shoal point energy": "shp",
  "shoal point energy ltd.": "shp",
  "shp": "shp",
  "shrc": "shrc",
  "shrm": "shrm",
  "shv": "shv",
  "sierra": "sgro",
  "sierra growth": "sgro",
  "sierra growth corp.": "sgro",
  "sig": "sig",
  "silver": "sand",
  "silver dollar": "slv",
  "silver dollar resources": "slv",
  "silver dollar resources inc.": "slv",
  "silver phoenix": "sp",
  "silver phoenix resources": "sp",
  "silver phoenix resources inc.": "sp",
  "silver sands": "sand",
  "silver sands resources": "sand",
  "silver sands resources corp.": "sand",
  "silver sands resources corp. (formerly": "sand",
  "silver sands resources corp. (formerly was goop/golden opportunity resources corp. until 2020-06-05)": "sand",
  "sire": "sire",
  "sire bioscience": "sire",
  "sire bioscience inc.": "sire",
  "sitka": "sig",
  "sitka gold": "sig",
  "sitka gold corp.": "sig",
  "six": "six",
  "sixth": "sixw",
  "sixth wave": "sixw",
  "sixth wave innovations": "sixw",
  "sixth wave innovations inc.": "sixw",
  "sixty": "sxty",
  "sixty north": "sxty",
  "sixty north gold": "sxty",
  "sixty north gold mining": "sxty",
  "sixty north gold mining inc.": "sxty",
  "sixw": "sixw",
  "size": "size",
  "skarb": "skrb",
  "skarb exploration": "skrb",
  "skarb exploration corp.": "skrb",
  "skrb": "skrb",
  "skyl": "skyl",
  "skyledger": "skyl",
  "skyledger tech": "skyl",
  "skyledger tech corp.": "skyl",
  "slang": "slng",
  "slang worldwide": "slng",
  "slang worldwide inc.": "slng",
  "slave": "slz",
  "slave lake": "slz",
  "slave lake zinc": "slz",
  "slave lake zinc corp": "slz",
  "sle": "sle",
  "sle synergy": "sle",
  "sle synergy ltd.": "sle",
  "slng": "slng",
  "slv": "slv",
  "slz": "slz",
  "sna": "sna",
  "snl": "snl",
  "snn": "snn",
  "soft": "soft",
  "softlab9": "soft",
  "softlab9 technologies": "soft",
  "softlab9 technologies inc.": "soft",
  "softlab9 technologies inc. (formerly": "soft",
  "softlab9 technologies inc. (formerly was": "soft",
  "softlab9 technologies inc. (formerly was soft/softlab9 software solutions inc until 2020-07-17)": "soft",
  "sol": "sol",
  "sol global": "sol",
  "sol global investments": "sol",
  "sol global investments corp.": "sol",
  "sona": "sona",
  "sona nanotech": "sona",
  "sona nanotech inc.": "sona",
  "sow": "sow",
  "sp": "sp",
  "spacefy": "spfy",
  "spacefy inc.": "spfy",
  "speakeasy": "easy",
  "speakeasy cannabis": "easy",
  "speakeasy cannabis club": "easy",
  "speakeasy cannabis club ltd.": "easy",
  "spearmint": "spmt",
  "spearmint resources": "spmt",
  "spearmint resources inc.": "spmt",
  "spey": "spey",
  "spey resources": "spey",
  "spey resources corp.": "spey",
  "spfy": "spfy",
  "spmt": "spmt",
  "spo": "spo",
  "sponsorsone": "spo",
  "sponsorsone inc.": "spo",
  "spor": "spor",
  "spor.wt": "spor",
  "spr": "spr",
  "sproutly": "spr",
  "sproutly canada": "spr",
  "sproutly canada inc.": "spr",
  "sqid": "sqid",
  "sqid technologies": "sqid",
  "sqid technologies limited": "sqid",
  "squatex": "sqx",
  "squatex energy": "sqx",
  "squatex energy and": "sqx",
  "squatex energy and ressources": "sqx",
  "squatex energy and ressources inc.": "sqx",
  "sqx": "sqx",
  "ssvr": "ssvr",
  "st": "st",
  "st-georges": "sx",
  "st-georges eco-mining": "sx",
  "st-georges eco-mining corp.": "sx",
  "star": "sna",
  "star navigation": "sna",
  "star navigation systems": "sna",
  "star navigation systems group": "sna",
  "star navigation systems group ltd.": "sna",
  "starrex": "stx",
  "starrex international": "stx",
  "starrex international ltd.": "stx",
  "stem": "stem",
  "stem holdings": "stem",
  "stem holdings inc.": "stem",
  "stevens": "sg",
  "stevens gold": "sg",
  "stevens gold nevada": "sg",
  "stevens gold nevada inc.": "sg",
  "stil": "stil",
  "stillcanna": "stil",
  "stillcanna inc.": "stil",
  "straightup": "st",
  "straightup resources": "st",
  "straightup resources inc.": "st",
  "stx": "stx",
  "summa": "ssvr",
  "summa silver": "ssvr",
  "summa silver corp.": "ssvr",
  "summa silver corp. (formerly": "ssvr",
  "summa silver corp. (formerly was": "ssvr",
  "summa silver corp. (formerly was pgg/pinnacle north gold corp. until 2020-04-30)": "ssvr",
  "sun": "sun",
  "sunniva": "snn",
  "sunniva inc.": "snn",
  "sweet": "se",
  "sweet earth": "se",
  "sweet earth holdings": "se",
  "sweet earth holdings corporation": "se",
  "swis": "swis",
  "swis.wt": "swis",
  "sx": "sx",
  "sxty": "sxty",
  "sxx": "sxx",
  "taal": "taal",
  "taal distributed": "taal",
  "taal distributed information": "taal",
  "taal distributed information technologies": "taal",
  "taal distributed information technologies inc.": "taal",
  "taal distributed information technologies inc. (formerly was sqr/squire mining ltd. until 2019-12-13)": "taal",
  "taat": "taat",
  "taat lifestyle": "taat",
  "taat lifestyle &": "taat",
  "taat lifestyle & wellness": "taat",
  "taat lifestyle & wellness ltd.": "taat",
  "tai": "tai",
  "taiga": "tgc",
  "taiga gold": "tgc",
  "taiga gold corp": "tgc",
  "tak": "tak",
  "taku": "tak",
  "taku gold": "tak",
  "taku gold corp.": "tak",
  "talisker": "tsk",
  "talisker resources": "tsk",
  "talisker resources ltd.": "tsk",
  "talmora": "tai",
  "talmora diamond": "tai",
  "talmora diamond inc.": "tai",
  "tantalex": "ttx",
  "tantalex resources": "ttx",
  "tantalex resources corporation": "ttx",
  "tarachi": "trg",
  "tarachi gold": "trg",
  "tarachi gold corp.": "trg",
  "tarachi gold corp. (formerly": "trg",
  "tarachi gold corp. (formerly was": "trg",
  "tarachi gold corp. (formerly was kal/kal minerals corp until 2020-04-07)": "trg",
  "target": "tci",
  "target capital": "tci",
  "target capital inc.": "tci",
  "tartisan": "tn",
  "tartisan nickel": "tn",
  "tartisan nickel corp.": "tn",
  "tbi": "tbi",
  "tcan": "tcan",
  "tcan.wt": "tcan",
  "tcf": "tcf",
  "tci": "tci",
  "te": "te",
  "temas": "tmas",
  "temas resources": "tmas",
  "temas resources corp.": "tmas",
  "temp": "temp",
  "tempus": "temp",
  "tempus capital": "temp",
  "tempus capital inc.": "temp",
  "teno": "teno",
  "teq": "teq",
  "ter": "ter",
  "terra": "teno",
  "terra nova": "teno",
  "terra nova resources": "teno",
  "terra nova resources inc.": "teno",
  "terranueva": "teq",
  "terranueva corporation": "teq",
  "terrascend": "ter",
  "terrascend corp.": "ter",
  "tfc": "tfc",
  "tgc": "tgc",
  "tgif": "tgif",
  "tgif.db": "tgif",
  "tgif.wt": "tgif",
  "thc": "thc",
  "thc biomed": "thc",
  "thc biomed intl": "thc",
  "thc biomed intl ltd": "thc",
  "the alkaline": "wter",
  "the alkaline water": "wter",
  "the alkaline water company": "wter",
  "the alkaline water company inc.": "wter",
  "the tinley": "tny",
  "the tinley beverage": "tny",
  "the tinley beverage company": "tny",
  "the tinley beverage company inc.": "tny",
  "the very": "very",
  "the very good": "very",
  "the very good food": "very",
  "the very good food company": "very",
  "the very good food company inc.": "very",
  "thoughtful": "tbi",
  "thoughtful brands": "tbi",
  "thoughtful brands inc.": "tbi",
  "thoughtful brands inc. (formerly": "tbi",
  "thoughtful brands inc. (formerly was": "tbi",
  "thoughtful brands inc. (formerly was mota/mota ventures corp. until 2020-08-13)": "tbi",
  "threed": "idk",
  "threed capital": "idk",
  "threed capital inc.": "idk",
  "tilt": "tilt",
  "tilt holdings": "tilt",
  "tilt holdings inc.": "tilt",
  "tium.u": "tium",
  "tium.wt.u": "tium",
  "tkr": "tkr",
  "tlp.un": "tlp",
  "tmas": "tmas",
  "tmed": "tmed",
  "tn": "tn",
  "tny": "tny",
  "toc": "toc",
  "tocvan": "toc",
  "tocvan ventures": "toc",
  "tocvan ventures corp.": "toc",
  "toki": "toki",
  "top": "veni",
  "top exploration": "te",
  "top exploration inc.": "te",
  "top strike": "veni",
  "top strike resources": "veni",
  "top strike resources corp.": "veni",
  "tower": "to",
  "tower one": "to",
  "tower one wireless": "to",
  "tower one wireless corp.": "to",
  "tracesafe": "tsf",
  "tracesafe inc.": "tsf",
  "tracesafe inc. (formerly": "tsf",
  "tracesafe inc. (formerly was": "tsf",
  "tracesafe inc. (formerly was bcx/blockchain": "tsf",
  "tracesafe inc. (formerly was bcx/blockchain holdings ltd. until 2020-06-18)": "tsf",
  "tracker": "tkr",
  "tracker ventures": "tkr",
  "tracker ventures corp.": "tkr",
  "tracker ventures corp. (formerly": "tkr",
  "tracker ventures corp. (formerly was": "tkr",
  "tracker ventures corp. (formerly was tool/trackloop analytics corp. until 2019-10-24)": "tkr",
  "transcanna": "tcan",
  "transcanna holdings": "tcan",
  "transcanna holdings inc.": "tcan",
  "tree": "toki",
  "tree of": "toki",
  "tree of knowledge": "toki",
  "tree of knowledge international": "toki",
  "tree of knowledge international corp.": "toki",
  "trg": "trg",
  "trichome": "tfc",
  "trichome financial": "tfc",
  "trichome financial corp.": "tfc",
  "trillion": "tcf",
  "trillion energy": "tcf",
  "trillion energy international": "tcf",
  "trillion energy international inc.": "tcf",
  "trip": "trip",
  "true": "mj",
  "true leaf": "mj",
  "true leaf brands": "mj",
  "true leaf brands inc.": "mj",
  "trul": "trul",
  "trul.db.u": "trul",
  "trulieve": "trul",
  "trulieve cannabis": "trul",
  "trulieve cannabis corp.": "trul",
  "trutrace": "ttt",
  "trutrace technologies": "ttt",
  "trutrace technologies inc.": "ttt",
  "tsf": "tsf",
  "tsk": "tsk",
  "ttt": "ttt",
  "ttx": "ttx",
  "tusk": "tusk",
  "twx.x": "twx",
  "uav": "uav",
  "ubique": "ubq",
  "ubique minerals": "ubq",
  "ubique minerals limited": "ubq",
  "ubm": "ubm",
  "ubq": "ubq",
  "united": "ubm",
  "united battery": "ubm",
  "united battery metals": "ubm",
  "united battery metals corp.": "ubm",
  "upco": "upco",
  "upco international": "upco",
  "upco international inc": "upco",
  "upsnap": "up",
  "upsnap inc.": "up",
  "urb": "urb",
  "urb.a": "urb",
  "urbana": "urb",
  "urbana corporation": "urb",
  "url": "url",
  "usgd": "usgd",
  "vai": "vai",
  "valeo": "vph",
  "valeo pharma": "vph",
  "valeo pharma inc.": "vph",
  "vc": "vc",
  "vcan": "vcan",
  "vct.x": "vct",
  "vega": "vega",
  "vegaste": "vega",
  "vegaste technologies": "vega",
  "vegaste technologies corp.": "vega",
  "veni": "veni",
  "ventura": "vcan",
  "ventura cannabis": "vcan",
  "ventura cannabis and": "vcan",
  "ventura cannabis and wellness": "vcan",
  "ventura cannabis and wellness corp.": "vcan",
  "veritas": "vrt",
  "veritas pharma": "vrt",
  "veritas pharma inc.": "vrt",
  "versus": "vs",
  "versus systems": "vs",
  "versus systems inc.": "vs",
  "vert": "vvv",
  "vert infrastructure": "vvv",
  "vert infrastructure ltd.": "vvv",
  "vert infrastructure ltd. (formerly": "vvv",
  "vert infrastructure ltd. (formerly was": "vvv",
  "vert infrastructure ltd. (formerly was crop/crop infrastructure corp. until 2020-01-15)": "vvv",
  "very": "very",
  "vext": "vext",
  "vext science,": "vext",
  "vext science, inc.": "vext",
  "vext science, inc. (formerly": "vext",
  "vext science, inc. (formerly was": "vext",
  "vext science, inc. (formerly was vapn/vapen mj ventures corporation until 2019-11-11)": "vext",
  "vibe": "vibe",
  "vibe bioscience": "vibe",
  "vibe bioscience ltd.": "vibe",
  "victory": "vst",
  "victory nickel": "ni",
  "victory nickel inc.": "ni",
  "victory resources": "vr",
  "victory resources corporation": "vr",
  "victory square": "vst",
  "victory square technologies": "vst",
  "victory square technologies inc.": "vst",
  "vida": "vida",
  "vin": "vin",
  "vinergy": "vin",
  "vinergy cannabis": "vin",
  "vinergy cannabis capital": "vin",
  "vinergy cannabis capital inc.": "vin",
  "vireo": "vreo",
  "vireo health": "vreo",
  "vireo health international": "vreo",
  "vireo health international inc.": "vreo",
  "vireo health international inc. s.v.": "vreo",
  "virtualarmour": "vai",
  "virtualarmour international": "vai",
  "virtualarmour international inc.": "vai",
  "vodis": "vp",
  "vodis pharmaceuticals": "vp",
  "vodis pharmaceuticals inc.": "vp",
  "volatus": "vc",
  "volatus capital": "vc",
  "volatus capital corp.": "vc",
  "voy": "voy",
  "voyager": "vygr",
  "voyager digital": "vygr",
  "voyager digital ltd.": "vygr",
  "voyager digital ltd. (formerly": "vygr",
  "voyager digital ltd. (formerly was": "vygr",
  "voyager digital ltd. (formerly was vygr/voyager digital (canada) ltd. until 2020-07-15)": "vygr",
  "voyageur": "voy",
  "voyageur mineral": "voy",
  "voyageur mineral explorers": "voy",
  "voyageur mineral explorers corp.": "voy",
  "voyageur mineral explorers corp. (formerly": "voy",
  "voyageur mineral explorers corp. (formerly was czc/copper reef mining corp. until 2020-08-18)": "voy",
  "vp": "vp",
  "vph": "vph",
  "vph.wt": "vph",
  "vpn": "vpn",
  "vpn technologies": "vpn",
  "vpn technologies inc.": "vpn",
  "vpn technologies inc. (formerly": "vpn",
  "vpn technologies inc. (formerly was": "vpn",
  "vpn technologies inc. (formerly was saas/subscribe technologies inc. until 2020-02-27)": "vpn",
  "vr": "vr",
  "vreo": "vreo",
  "vrt": "vrt",
  "vs": "vs",
  "vsblty": "vsby",
  "vsblty groupe": "vsby",
  "vsblty groupe technologies": "vsby",
  "vsblty groupe technologies corp.": "vsby",
  "vsby": "vsby",
  "vst": "vst",
  "vvv": "vvv",
  "vygr": "vygr",
  "wal": "wal",
  "walcott": "wal",
  "walcott resources": "wal",
  "walcott resources ltd.": "wal",
  "wayl": "wayl",
  "wayl.wt": "wayl",
  "wayland": "wayl",
  "wayland group": "wayl",
  "wayland group corp.": "wayl",
  "wbio": "wbio",
  "weekend": "pot",
  "weekend unlimited": "pot",
  "weekend unlimited industries": "pot",
  "weekend unlimited industries inc.": "pot",
  "weekend unlimited industries inc. (formerly": "pot",
  "weekend unlimited industries inc. (formerly was pot/weekend unlimited inc. until 2020-01-20)": "pot",
  "west": "rlg",
  "west red": "rlg",
  "west red lake": "rlg",
  "west red lake gold": "rlg",
  "west red lake gold mines": "rlg",
  "west red lake gold mines inc.": "rlg",
  "western": "wuc",
  "western uranium": "wuc",
  "western uranium &": "wuc",
  "western uranium & vanadium": "wuc",
  "western uranium & vanadium corp.": "wuc",
  "wgc": "wgc",
  "wifi": "wifi",
  "wiki": "wiki",
  "wikileaf": "wiki",
  "wikileaf technologies": "wiki",
  "wikileaf technologies inc.": "wiki",
  "wildflower": "sun",
  "wildflower brands": "sun",
  "wildflower brands inc.": "sun",
  "winston": "wgc",
  "winston gold": "wgc",
  "winston gold corp.": "wgc",
  "world": "pump",
  "world class": "pump",
  "world class extractions": "pump",
  "world class extractions inc.": "pump",
  "wpd": "wbio",
  "wpd pharmaceuticals": "wbio",
  "wpd pharmaceuticals inc.": "wbio",
  "wpd pharmaceuticals inc. (formerly": "wbio",
  "wpd pharmaceuticals inc. (formerly was": "wbio",
  "wpd pharmaceuticals inc. (formerly was wbio/westcot ventures corp. until 2020-01-13)": "wbio",
  "wpn": "wpn",
  "wsm.x": "wsm",
  "wter": "wter",
  "wuc": "wuc",
  "xblk": "xblk",
  "xcx": "xcx",
  "xmg": "xmg",
  "xmg.wt.b": "xmg",
  "xmg.wt.c": "xmg",
  "xop": "xop",
  "xortx": "xrx",
  "xortx therapeutics": "xrx",
  "xortx therapeutics inc.": "xrx",
  "xphy": "xphy",
  "xphyto": "xphy",
  "xphyto therapeutics": "xphy",
  "xphyto therapeutics corp.": "xphy",
  "xro": "xro",
  "xrx": "xrx",
  "xs": "xsf",
  "xs financial": "xsf",
  "xs financial inc.": "xsf",
  "xs financial inc. (formerly": "xsf",
  "xs financial inc. (formerly was": "xsf",
  "xs financial inc. (formerly was xs/xtraction services holdings corp until 2020-06-25)": "xsf",
  "xsf": "xsf",
  "xtm": "paid",
  "xtm inc.": "paid",
  "xtrx": "xtrx",
  "yt": "yt",
  "yukoterre": "yt",
  "yukoterre resources": "yt",
  "yukoterre resources inc.": "yt",
  "zair": "zair",
  "zanzibar": "zbr",
  "zanzibar gold": "zbr",
  "zanzibar gold inc.": "zbr",
  "zbr": "zbr",
  "zenith": "zx",
  "zenith exploration": "zx",
  "zenith exploration inc.": "zx",
  "zeu": "zeu",
  "zeu crypto": "zeu",
  "zeu crypto networks": "zeu",
  "zeu crypto networks inc.": "zeu",
  "zinc8": "zair",
  "zinc8 energy": "zair",
  "zinc8 energy solutions": "zair",
  "zinc8 energy solutions inc.": "zair",
  "zinc8 energy solutions inc. (formerly": "zair",
  "zinc8 energy solutions inc. (formerly was mgxr/mgx renewables inc. until 2020-03-20)": "zair",
  "znk": "znk",
  "zro": "zro",
  "zte": "zte",
  "ztest": "zte",
  "ztest electronics": "zte",
  "ztest electronics inc.": "zte",
  "zx": "zx"
}